
-- table creation --
drop database agrigo;
create database agrigo;
\c agrigo

CREATE TABLE GOVERNMENT
(USER_ID VARCHAR(16) UNIQUE,
USER_NAME VARCHAR(30),
JOB VARCHAR(30),
PASSWORD VARCHAR(30),
PRIMARY KEY(USER_ID)     );

CREATE TABLE BANK(
BANK_ID VARCHAR(18) UNIQUE,
BANK_NAME VARCHAR(30),
PRIMARY KEY(BANK_ID)
);


CREATE TABLE LOAN(
LOAN_ID VARCHAR(18) UNIQUE,
LOAN_AMOUNT INT,
PRIMARY KEY(LOAN_ID)
);

CREATE TABLE PLACE
(
PINCODE INT,
DOOR_NO INT,
ADDRESS  VARCHAR(50),
DISTRICT VARCHAR(30),
VILLAGE VARCHAR(30),
PRIMARY KEY(DOOR_NO)
);

CREATE TABLE FARMER
(
FARMER_ID VARCHAR(16) UNIQUE,
FARMER_NAME VARCHAR(30),
GENDER CHAR,
PHONE_NO VARCHAR(10),
ACRES INT,
WATER_TYPE VARCHAR(30),
D_NO INT,
L_ID VARCHAR(18) UNIQUE,
B_ID VARCHAR(18) UNIQUE,
PRIMARY KEY(FARMER_ID),
FOREIGN KEY (FARMER_ID) REFERENCES GOVERNMENT(USER_ID),
FOREIGN KEY (D_NO) REFERENCES PLACE(DOOR_NO),
FOREIGN KEY (L_ID) REFERENCES LOAN(LOAN_ID),
FOREIGN KEY (B_ID) REFERENCES BANK(BANK_ID)
);


CREATE TABLE SCHEME
(
SCHEME_ID VARCHAR UNIQUE,
COUNT_REGISTRATION INT,
BENEFITS VARCHAR,
SCHEME_NAME VARCHAR,
CRITERIA VARCHAR,
U_ID VARCHAR(16) UNIQUE,
PRIMARY KEY(SCHEME_ID),
FOREIGN KEY (U_ID) REFERENCES GOVERNMENT(USER_ID)
);


CREATE TABLE CROP
(
CROP_TYPE VARCHAR(30),
CROP_NAME VARCHAR(30),
QUANTITY INT,
FAR_ID VARCHAR(16),
FOREIGN KEY (FAR_ID) REFERENCES FARMER(FARMER_ID)
);

CREATE TABLE WAREHOUSE
(
WAREHOUSE_ID INT,
LOCATION VARCHAR(30),
OWNER VARCHAR(30),
CAPACITY INT,
PRIMARY KEY(WAREHOUSE_ID)
);


CREATE TABLE BUYER
(
BUYER_ID VARCHAR(16) UNIQUE,
BUYER_NAME VARCHAR(30),
WAR_ID INT,
PRIMARY KEY(BUYER_ID),
FOREIGN KEY (WAR_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID)
);


CREATE TABLE SUPPLIER
(
SUPPLIER_ID VARCHAR(16) UNIQUE,
SUPPLIER_NAME VARCHAR(30),
PRIMARY KEY(SUPPLIER_ID)
);

CREATE TABLE REQUIREMENTS
(
PESTICIDE VARCHAR(30),
FERTILIZER VARCHAR(30),
SEED VARCHAR(30),
FAR_ID VARCHAR(16) UNIQUE,
QUANTITY INT,
FOREIGN KEY (FAR_ID) REFERENCES FARMER(FARMER_ID)
);

CREATE TABLE OFFER
(
SUP_ID VARCHAR(16) UNIQUE,
FARM_ID VARCHAR(16) UNIQUE,
PRICE INT,
FOREIGN KEY (SUP_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
FOREIGN KEY (FARM_ID) REFERENCES FARMER(FARMER_ID)
);


CREATE TABLE REGISTER
(
SCH_ID VARCHAR(16) UNIQUE,
FARM_ID VARCHAR(16) UNIQUE,
FOREIGN KEY (SCH_ID) REFERENCES SCHEME(SCHEME_ID),
FOREIGN KEY (FARM_ID) REFERENCES FARMER(FARMER_ID)
);

CREATE TABLE STORED_AT
(cname VARCHAR(20),
farm_id VARCHAR(16),
WAR_ID INT,
FOREIGN KEY (farm_id) REFERENCES Farmer(farmer_id),
FOREIGN KEY (WAR_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID)
);

CREATE TABLE BUYS
(
BUYE_ID VARCHAR(16) UNIQUE,
farm_id VARCHAR(16) UNIQUE,
cname VARCHAR(20),
PRICE INT,
QUANTITY INT,
FOREIGN KEY (BUYE_ID) REFERENCES BUYER(BUYER_ID),
FOREIGN KEY (farm_id) REFERENCES Farmer(farmer_id));




